In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/metadata_cleaned.csv')

# Import the original file
orig_df = pd.read_csv('../data/movies_metadata.csv', low_memory=False)

# Load the keywords and credits files
cred_df = pd.read_csv('../data/credits.csv')
key_df = pd.read_csv('../data/keywords.csv')

df.head()

,title,genres,runtime,vote_average,vote_count,year
0,Toy Story,"['animation', 'comedy', 'family']",81.0,7.7,5415.0,1995
1,Jumanji,"['adventure', 'fantasy', 'family']",104.0,6.9,2413.0,1995
2,Grumpier Old Men,"['romance', 'comedy']",101.0,6.5,92.0,1995
3,Waiting to Exhale,"['comedy', 'drama', 'romance']",127.0,6.1,34.0,1995
4,Father of the Bride Part II,['comedy'],106.0,5.7,173.0,1995

In [13]:
# Print the head of the credit dataframe

cred_df.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [14]:
# Print the head of the keywords dataframe
key_df.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [15]:
# Add the useful features into the cleaned dataframe
df['overview'], df['id'] = orig_df['overview'], orig_df['id']

# Replace NaN with an empty string
df['overview'] = df['overview'].fillna('')


print(df.dtypes)

df.head()

title            object
genres           object
runtime         float64
vote_average    float64
vote_count      float64
year              int64
overview         object
id               object
dtype: object

,title,genres,runtime,vote_average,vote_count,year,overview,id
0,Toy Story,"['animation', 'comedy', 'family']",81.0,7.7,5415.0,1995,"Led by Woody, Andy's toys live happily in his ...",862
1,Jumanji,"['adventure', 'fantasy', 'family']",104.0,6.9,2413.0,1995,When siblings Judy and Peter discover an encha...,8844
2,Grumpier Old Men,"['romance', 'comedy']",101.0,6.5,92.0,1995,A family wedding reignites the ancient feud be...,15602
3,Waiting to Exhale,"['comedy', 'drama', 'romance']",127.0,6.1,34.0,1995,"Cheated on, mistreated and stepped on, the wom...",31357
4,Father of the Bride Part II,['comedy'],106.0,5.7,173.0,1995,Just when George Banks has recovered from his ...,11862

In [16]:
# Convert the IDs of df into int
df['id'] = df['id'].astype('int')

ValueError: invalid literal for int() with base 10: '1997-08-20'

In [17]:
# Function to convert all non-integer IDs to NaN

def clean_ids(x):
    try:
        return int(x)
    except:
        return np.nan

In [18]:
# Clean the ids of df
df['id'] = df['id'].apply(clean_ids)

# Filter all rows that have a null ID
df = df[df['id'].notnull()]

In [19]:
# Convert the IDs into integer
df['id'] = df['id'].astype('int')
key_df['id'] = key_df['id'].astype('int')
cred_df['id'] = cred_df['id'].astype('int')

# Merge keywords and credits into your main metatdata dataframe
df = df.merge(cred_df, on='id')
df = df.merge(key_df, on='id')

# Display the head of df
df.head()

,title,genres,runtime,vote_average,vote_count,year,overview,id,cast,crew,keywords
0,Toy Story,"['animation', 'comedy', 'family']",81.0,7.7,5415.0,1995,"Led by Woody, Andy's toys live happily in his ...",862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,Jumanji,"['adventure', 'fantasy', 'family']",104.0,6.9,2413.0,1995,When siblings Judy and Peter discover an encha...,8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,Grumpier Old Men,"['romance', 'comedy']",101.0,6.5,92.0,1995,A family wedding reignites the ancient feud be...,15602,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,Waiting to Exhale,"['comedy', 'drama', 'romance']",127.0,6.1,34.0,1995,"Cheated on, mistreated and stepped on, the wom...",31357,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,Father of the Bride Part II,['comedy'],106.0,5.7,173.0,1995,Just when George Banks has recovered from his ...,11862,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [20]:
# Convert the stringified objects into the native python objects

from ast import literal_eval

features = ['cast', 'crew', 'keywords', 'genres']
for feature in features:
    df[feature] = df[feature].apply(literal_eval)

In [21]:
# Print the first cast member of the first movie in df

# df  →  a big cabinet (DataFrame)
# iloc[0]  →  open the first drawer (row)
# ['crew'] →  pick the “crew” folder inside it (column)
# [0]  →  take the first page in that folder (first dictionary)
# 🥇 df.iloc[0]

# .iloc means “index location”.

# So df.iloc[0] means:
# 👉 “Give me the first row of the DataFrame.”

# | Expression              | Meaning                                     | Output type     |
# | ----------------------- | ------------------------------------------- | --------------- |
# | `df`                    | The whole DataFrame                         | DataFrame       |
# | `df.iloc[0]`            | The first row                               | Series          |
# | `df.iloc[0]['crew']`    | The value in the `crew` column for that row | List (of dicts) |
# | `df.iloc[0]['crew'][0]` | The first item (dict) inside that list      | Dict            |


df.iloc[0]['crew'][0]

{'credit_id': '52fe4284c3a36847f8024f49',
 'department': 'Directing',
 'gender': 2,
 'id': 7879,
 'job': 'Director',
 'name': 'John Lasseter',
 'profile_path': '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg'}

In [22]:
# Extract the director's name. If director is not listed, return NaN

def get_director(x):
    for crew_member in x:
        if crew_member['job'] == 'Director':
            return crew_member['name']
    return np.nan

In [23]:
# Define the new director feature

df['director'] = df['crew'].apply(get_director)

# Print the directors of the first five movies
df['director'].head()

0      John Lasseter
1       Joe Johnston
2      Howard Deutch
3    Forest Whitaker
4      Charles Shyer
Name: director, dtype: object

In [24]:
# Returns the list top 3 elements or entire list; whichever is more.

def generate_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]

        # Check if more than 3 elements exist. If yes, return only first three.
        # If no, return entire list.

        if len(names) > 3:
            names = names[:3]
        return names

    # Return empty list in case of missing/malformed data
    return []

In [25]:
# Apply the generate_list function to cast and keywords
df['cast'] = df['cast'].apply(generate_list)
df['keywords'] = df['keywords'].apply(generate_list)

In [26]:
# Only consider a maximum of 3 genres
df['genres'] = df['genres'].apply(lambda x: x[:3])

In [27]:
# Print the new features of the first 5 movies along with title
df[['title', 'cast', 'director', 'keywords', 'genres']].head()

,title,cast,director,keywords,genres
0,Toy Story,"[Tom Hanks, Tim Allen, Don Rickles]",John Lasseter,"[jealousy, toy, boy]","[animation, comedy, family]"
1,Jumanji,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",Joe Johnston,"[board game, disappearance, based on children'...","[adventure, fantasy, family]"
2,Grumpier Old Men,"[Walter Matthau, Jack Lemmon, Ann-Margret]",Howard Deutch,"[fishing, best friend, duringcreditsstinger]","[romance, comedy]"
3,Waiting to Exhale,"[Whitney Houston, Angela Bassett, Loretta Devine]",Forest Whitaker,"[based on novel, interracial relationship, sin...","[comedy, drama, romance]"
4,Father of the Bride Part II,"[Steve Martin, Diane Keaton, Martin Short]",Charles Shyer,"[baby, midlife crisis, confidence]",[comedy]

In [28]:
# Function to sanitize data to prevent ambiguity. It removes spaces and converts to lowercase

def sanitize(x):
    if isinstance(x, list):
        # Strip spaces and converts to lowercase
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        # Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''


# 1️⃣ Why we sanitize

# Sanitizing means cleaning the data to remove inconsistencies, like:

# Extra spaces: "Science Fiction " vs "Science Fiction"

# Capitalization differences: "Action" vs "action"

# Formatting issues in lists: "Christopher Nolan" vs " christopher nolan "

# If we don’t sanitize, the computer sees these as different values, even though they represent the same thing.

# 2️⃣ Example in a movie recommender

# Suppose you have genres like this:

# movie	genres
# Movie A	["Action", "Thriller"]
# Movie B	["action", "thriller "]
# Without sanitization:

# "Action" ≠ "action"

# "Thriller" ≠ "thriller "

# Cosine similarity or other matching algorithms will treat these movies as less similar than they really are.

# With sanitization:

# Convert everything to lowercase and remove spaces → ["action","thriller"] for both movies

# Now the algorithm correctly sees them as similar.

# 3️⃣ What happens if we don’t sanitize

# Reduced accuracy: Movies that are actually similar may not be recognized as such.

# Inconsistent results: Searching by cast, director, or genre may fail to match correctly.

# Duplicate entries: Slight variations in text may create “different” items that are really the same.

# 4️⃣ Summary
# Before sanitize	After sanitize	Problem solved
# "Action"	"action"	Case sensitivity
# "Science Fiction "	"sciencefiction"	Extra spaces
# "Christopher Nolan"	"christophernolan"	Uniform text for matching

# ✅ In short:
# Sanitization ensures the recommender system can correctly compare movies. Without it, the algorithm may underestimate similarity or give wrong recommendations.

In [29]:
# Apply the sanitize function to cast, keywords, director and genres
for feature in ['cast', 'director', 'genres', 'keywords']:
    df[feature] = df[feature].apply(sanitize)


### 1️⃣ The function:

```python
# Function that creates a soup out of the desired metadata
def create_soup(x):
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])
```

---

### 2️⃣ What “soup” means here

* **This `soup` is not BeautifulSoup**.
* In this context, “soup” is just a **term used in NLP/data processing**: it means **a single string that combines multiple pieces of text data**.
* Basically, we’re “mixing all metadata into one text blob” so that we can later convert it into a **vector for similarity calculations** (like TF-IDF or CountVectorizer).

---

### 3️⃣ Step-by-step explanation

* `x['keywords']` → a list of keywords

  * `' '.join(x['keywords'])` → joins them into a single string separated by spaces
* `x['cast']` → a list of cast member names

  * `' '.join(x['cast'])` → joins them into a single string
* `x['director']` → a single string (director name)
* `x['genres']` → a list of genres

  * `' '.join(x['genres'])` → joins them into a single string

Then all these strings are concatenated with `' '` (spaces) between them.

---

### 4️⃣ Example

Suppose a movie row looks like this:

```python
x = {
    'keywords': ['dream', 'subconscious'],
    'cast': ['Leonardo DiCaprio', 'Joseph Gordon-Levitt'],
    'director': 'Christopher Nolan',
    'genres': ['Action', 'Sci-Fi']
}
```

Calling:

```python
create_soup(x)
```

Returns:

```
'dream subconscious Leonardo DiCaprio Joseph Gordon-Levitt Christopher Nolan Action Sci-Fi'
```

✅ Now you have **one big string** representing all relevant metadata for that movie.

---

### 5️⃣ Why do this?

* To feed it into **vectorizers** like `CountVectorizer` or `TfidfVectorizer`
* This allows the recommender system to **compute similarity** between movies based on all metadata at once.

---

### 🧠 Analogy

Think of each movie’s metadata as ingredients:

* keywords → sugar
* cast → flour
* director → eggs
* genres → chocolate

`create_soup` **mixes them all together** into one “cake batter” (soup) that the similarity algorithm can taste (analyze).

---

So in this context, **“soup” just means a single combined string**.

In [ ]:
# Function that creates a soup out of the desired metadata

def create_soup(x):
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])

In [31]:
# Create the new soup feature
df['soup'] = df.apply(create_soup, axis=1)

In [32]:
# Display the soup of the first movie

df.iloc[0]['soup']

'jealousy toy boy tomhanks timallen donrickles johnlasseter animation comedy family'

In [34]:
# Import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# Define a new CountVecotrizer object and create vectors for the soup
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(df['soup'])

In [35]:
# Import cosine_similarity function
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity score(equivalent to dot product for tf-idf vectors)
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [36]:
# Reset index of your df and construct reverse mapping again
df = df.reset_index()
indices2 = pd.Series(df.index, index=df['title'])

In [43]:
# Function that takes in movie title as input and gives recommendations
def content_recommender(title, cosine_sim=cosine_sim2, df=df, indices=indices2):
    # Obtain the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    # And convert it into a list of tuples as described above
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the cosine similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies. Ignore the first movie.
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df['title'].iloc[movie_indices]

In [44]:
content_recommender('The Lion King', cosine_sim2, df, indices2)

29569                                          Cheburashka
40884                   VeggieTales: Josh and the Big Wall
40893    VeggieTales: Minnesota Cuke and the Search for...
27722                                 The Little Matchgirl
15130             Spiderman: The Ultimate Villain Showdown
16534                            Cirque du Soleil: Varekai
24600                                  The Seventh Brother
29156                                      Superstar Goofy
30210                                              My Love
31145                Pokémon: Arceus and the Jewel of Life
Name: title, dtype: object